# Generated by Django 2.1.3 on 2018-11-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimemanagement', '0004_auto_20181120_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
    ]
