# Generated by Django 2.1.3 on 2018-11-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimemanagement', '0005_auto_20181120_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'managed': False},
        ),
    ]
