# Generated by Django 2.1.3 on 2018-11-20 13:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('crimemanagement', '0007_auto_20181120_1845'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auth',
            managers=[
                ('auth', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='complaint',
            managers=[
                ('complaint', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='crime',
            managers=[
                ('crime', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='crime',
            name='crime',
        ),
    ]
