# Generated by Django 2.1.3 on 2018-11-21 11:40

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crimemanagement', '0008_auto_20181120_1922'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crime',
            managers=[
                ('crimes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='crime',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
